# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24d7b189f7541e620085088654d4d373ac423fe763a970772c58204187bd020990ed3211fde9a0fe3c1799ec6a39c3d674f0a4b1fabe0941d60892ced623b6fe

test:
  secret_key_base: e12758112f75fc37b78555688a1b23d2dabf660c8bc50fcd407442ed3ad4e01cf8e9dfe5a63c359bdc0528cf9b5c8928e1fb881a0ef5f4833a2533c244968189

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
